[package]
name = "lab01"
version = "0.1.0"
authors = ["Russ Webber <russ@rw.id.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
